export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    REGISTER_IMG_REQUEST: 'USERS_REGISTER_IMG_REQUEST',
    REGISTER_IMG_SUCCESS: 'USERS_REGISTER_IMG_SUCCESS',
    REGISTER_IMG_FAILURE:'USERS_REGISTER_IMG_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    GET_IMAGE_REQUEST:'USERS_GET_IMAGE_REQUEST',
    GET_IMAGE_SUCCESS:'USERS_GET_IMAGE_SUCCESS',
    GET_IMAGE_FAILURE:'USERS_GET_IMAGE_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',

    GETBYID_REQUEST: 'USER_GETBYID_REQUEST',
    GETBYID_SUCCESS: 'USER_GETBYID_SUCCESS',
    GETBYID_FAILURE: 'USER_GETBYID_FAILURE',

    UPDATE_REQUEST:'USER_UPDATE_REQUEST',
    UPDATE_SUCCESS:'USER_UPDATE_SUCCESS',
    UPDATE_FAILURE:'USER_UPDATE_FAILURE',

    LIKES_REQUEST:'USERS_LIKES_REQUEST',
    LIKES_SUCCESS:'USERS_LIKES_SUCCESS',
    LIKES_FAILURE:'USERS_LIKES_FAILURE',

    COMMENTS_REQUEST:'USERS_COMMENTS_REQUEST',
    COMMENTS_SUCCESS:'USERS_COMMENTS_SUCCESS',
    COMMENTS_FAILURE:'USERS_COMMENTS_FAILURE',

    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};

